### ISSUE TITLE
Crash on MC 1.12.2 - 1.12.4

### ISSUE THREAD

**Issue by Tom1817** [811Alex/Quickcraft#6]
Hi, do you plan to update this for 1.21.3/4? It doesn't prevent loading, but doing shift+ctrl+click to craft all crashes MC with the attached report
[crash-2024-12-13_00.37.40-client.txt](https://github.com/user-attachments/files/18119098/crash-2024-12-13_00.37.40-client.txt)

**Comment by appelmoesgg** [comment]
I updated it to 1.21.4 and I am waiting for my pull request to get accepted...
https://github.com/appelmoesgg/Quickcraft
